# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/python/3.12.1/lib/python3.12/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /usr/local/python/3.12.1/lib/python3.12/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/Programmentwurf_cj

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/Programmentwurf_cj

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/local/python/3.12.1/lib/python3.12/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/python/3.12.1/lib/python3.12/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/Programmentwurf_cj/CMakeFiles /workspaces/Programmentwurf_cj//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/Programmentwurf_cj/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Program_lib

# Build rule for target.
Program_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Program_lib
.PHONY : Program_lib

# fast build rule for target.
Program_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Program_lib.dir/build.make CMakeFiles/Program_lib.dir/build
.PHONY : Program_lib/fast

#=============================================================================
# Target rules for targets named Programmentwurf

# Build rule for target.
Programmentwurf: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Programmentwurf
.PHONY : Programmentwurf

# fast build rule for target.
Programmentwurf/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Programmentwurf.dir/build.make CMakeFiles/Programmentwurf.dir/build
.PHONY : Programmentwurf/fast

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Programmentwurf.dir/build.make CMakeFiles/Programmentwurf.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Programmentwurf.dir/build.make CMakeFiles/Programmentwurf.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Programmentwurf.dir/build.make CMakeFiles/Programmentwurf.dir/main.c.s
.PHONY : main.c.s

src/developer.o: src/developer.c.o
.PHONY : src/developer.o

# target to build an object file
src/developer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Program_lib.dir/build.make CMakeFiles/Program_lib.dir/src/developer.c.o
.PHONY : src/developer.c.o

src/developer.i: src/developer.c.i
.PHONY : src/developer.i

# target to preprocess a source file
src/developer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Program_lib.dir/build.make CMakeFiles/Program_lib.dir/src/developer.c.i
.PHONY : src/developer.c.i

src/developer.s: src/developer.c.s
.PHONY : src/developer.s

# target to generate assembly for a file
src/developer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Program_lib.dir/build.make CMakeFiles/Program_lib.dir/src/developer.c.s
.PHONY : src/developer.c.s

src/developer_group.o: src/developer_group.c.o
.PHONY : src/developer_group.o

# target to build an object file
src/developer_group.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Program_lib.dir/build.make CMakeFiles/Program_lib.dir/src/developer_group.c.o
.PHONY : src/developer_group.c.o

src/developer_group.i: src/developer_group.c.i
.PHONY : src/developer_group.i

# target to preprocess a source file
src/developer_group.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Program_lib.dir/build.make CMakeFiles/Program_lib.dir/src/developer_group.c.i
.PHONY : src/developer_group.c.i

src/developer_group.s: src/developer_group.c.s
.PHONY : src/developer_group.s

# target to generate assembly for a file
src/developer_group.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Program_lib.dir/build.make CMakeFiles/Program_lib.dir/src/developer_group.c.s
.PHONY : src/developer_group.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Program_lib"
	@echo "... Programmentwurf"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/developer.o"
	@echo "... src/developer.i"
	@echo "... src/developer.s"
	@echo "... src/developer_group.o"
	@echo "... src/developer_group.i"
	@echo "... src/developer_group.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

